[package]
authors = ["Paweł Jankiewicz <p.jankiewicz@gmail.com>"]
edition = "2018"
name = "image-embedding-rust"
version = "0.1.0"
[dependencies]
clap = "3.0.0-beta.2"
image = "*"
tract = "*"
tract-onnx = "*"
